package zio.blocks.template

import zio.blocks.chunk.Chunk

trait HtmlElements {

  // --- Element constructors ---

  private def elScript(modifiers: Seq[Modifier]): Dom.Element.Script = {
    var elem: Dom.Element.Script = Dom.Element.Script(Chunk.empty, Chunk.empty)
    var i                        = 0
    while (i < modifiers.length) {
      val applied = modifiers(i).applyTo(elem)
      elem = applied match {
        case s: Dom.Element.Script => s
        case other                 => Dom.Element.Script(other.attributes, other.children)
      }
      i += 1
    }
    elem
  }

  private def elStyle(modifiers: Seq[Modifier]): Dom.Element.Style = {
    var elem: Dom.Element.Style = Dom.Element.Style(Chunk.empty, Chunk.empty)
    var i                       = 0
    while (i < modifiers.length) {
      val applied = modifiers(i).applyTo(elem)
      elem = applied match {
        case s: Dom.Element.Style => s
        case other                => Dom.Element.Style(other.attributes, other.children)
      }
      i += 1
    }
    elem
  }

  val html: Tag                                                            = new Tag("html")
  val head: Tag                                                            = new Tag("head")
  val body: Tag                                                            = new Tag("body")
  val title: Tag                                                           = new Tag("title")
  val div: Tag                                                             = new Tag("div")
  val span: Tag                                                            = new Tag("span")
  val p: Tag                                                               = new Tag("p")
  val h1: Tag                                                              = new Tag("h1")
  val h2: Tag                                                              = new Tag("h2")
  val h3: Tag                                                              = new Tag("h3")
  val h4: Tag                                                              = new Tag("h4")
  val h5: Tag                                                              = new Tag("h5")
  val h6: Tag                                                              = new Tag("h6")
  val a: Tag                                                               = new Tag("a")
  val abbr: Tag                                                            = new Tag("abbr")
  val address: Tag                                                         = new Tag("address")
  val area: Tag                                                            = new Tag("area")
  val article: Tag                                                         = new Tag("article")
  val aside: Tag                                                           = new Tag("aside")
  val audio: Tag                                                           = new Tag("audio")
  val b: Tag                                                               = new Tag("b")
  val base: Tag                                                            = new Tag("base")
  val bdi: Tag                                                             = new Tag("bdi")
  val bdo: Tag                                                             = new Tag("bdo")
  val blockquote: Tag                                                      = new Tag("blockquote")
  val br: Tag                                                              = new Tag("br")
  val button: Tag                                                          = new Tag("button")
  val canvas: Tag                                                          = new Tag("canvas")
  val caption: Tag                                                         = new Tag("caption")
  val cite: Tag                                                            = new Tag("cite")
  val code: Tag                                                            = new Tag("code")
  val col: Tag                                                             = new Tag("col")
  val colgroup: Tag                                                        = new Tag("colgroup")
  val data: Tag                                                            = new Tag("data")
  val datalist: Tag                                                        = new Tag("datalist")
  val dd: Tag                                                              = new Tag("dd")
  val del: Tag                                                             = new Tag("del")
  val details: Tag                                                         = new Tag("details")
  val dfn: Tag                                                             = new Tag("dfn")
  val dialog: Tag                                                          = new Tag("dialog")
  val dl: Tag                                                              = new Tag("dl")
  val dt: Tag                                                              = new Tag("dt")
  val em: Tag                                                              = new Tag("em")
  val embed: Tag                                                           = new Tag("embed")
  val fieldset: Tag                                                        = new Tag("fieldset")
  val figure: Tag                                                          = new Tag("figure")
  val figcaption: Tag                                                      = new Tag("figcaption")
  val footer: Tag                                                          = new Tag("footer")
  val form: Tag                                                            = new Tag("form")
  val header: Tag                                                          = new Tag("header")
  val hr: Tag                                                              = new Tag("hr")
  val i: Tag                                                               = new Tag("i")
  val iframe: Tag                                                          = new Tag("iframe")
  val img: Tag                                                             = new Tag("img")
  val input: Tag                                                           = new Tag("input")
  val ins: Tag                                                             = new Tag("ins")
  val kbd: Tag                                                             = new Tag("kbd")
  val label: Tag                                                           = new Tag("label")
  val legend: Tag                                                          = new Tag("legend")
  val li: Tag                                                              = new Tag("li")
  val link: Tag                                                            = new Tag("link")
  val main: Tag                                                            = new Tag("main")
  val map: Tag                                                             = new Tag("map")
  val mark: Tag                                                            = new Tag("mark")
  val math: Tag                                                            = new Tag("math")
  val meta: Tag                                                            = new Tag("meta")
  val meter: Tag                                                           = new Tag("meter")
  val nav: Tag                                                             = new Tag("nav")
  val noscript: Tag                                                        = new Tag("noscript")
  val `object`: Tag                                                        = new Tag("object")
  val objectTag: Tag                                                       = new Tag("object")
  val ol: Tag                                                              = new Tag("ol")
  val optgroup: Tag                                                        = new Tag("optgroup")
  val option: Tag                                                          = new Tag("option")
  val output: Tag                                                          = new Tag("output")
  val param: Tag                                                           = new Tag("param")
  val picture: Tag                                                         = new Tag("picture")
  val pre: Tag                                                             = new Tag("pre")
  val progress: Tag                                                        = new Tag("progress")
  val q: Tag                                                               = new Tag("q")
  val rp: Tag                                                              = new Tag("rp")
  val rt: Tag                                                              = new Tag("rt")
  val ruby: Tag                                                            = new Tag("ruby")
  val s: Tag                                                               = new Tag("s")
  val samp: Tag                                                            = new Tag("samp")
  def script(): Dom.Element.Script                                         = elScript(Seq.empty)
  def script(modifier: Modifier, modifiers: Modifier*): Dom.Element.Script = elScript(Seq(modifier) ++ modifiers)
  val search: Tag                                                          = new Tag("search")
  val section: Tag                                                         = new Tag("section")
  val select: Tag                                                          = new Tag("select")
  val slot: Tag                                                            = new Tag("slot")
  val small: Tag                                                           = new Tag("small")
  val source: Tag                                                          = new Tag("source")
  val strong: Tag                                                          = new Tag("strong")
  def style(): Dom.Element.Style                                           = elStyle(Seq.empty)
  def style(modifier: Modifier, modifiers: Modifier*): Dom.Element.Style   = elStyle(Seq(modifier) ++ modifiers)
  val sub: Tag                                                             = new Tag("sub")
  val summary: Tag                                                         = new Tag("summary")
  val sup: Tag                                                             = new Tag("sup")
  val svg: Tag                                                             = new Tag("svg")
  val table: Tag                                                           = new Tag("table")
  val tbody: Tag                                                           = new Tag("tbody")
  val td: Tag                                                              = new Tag("td")
  val `template`: Tag                                                      = new Tag("template")
  val templateTag: Tag                                                     = new Tag("template")
  val textarea: Tag                                                        = new Tag("textarea")
  val tfoot: Tag                                                           = new Tag("tfoot")
  val th: Tag                                                              = new Tag("th")
  val thead: Tag                                                           = new Tag("thead")
  val time: Tag                                                            = new Tag("time")
  val tr: Tag                                                              = new Tag("tr")
  val track: Tag                                                           = new Tag("track")
  val u: Tag                                                               = new Tag("u")
  val ul: Tag                                                              = new Tag("ul")
  val `var`: Tag                                                           = new Tag("var")
  val varTag: Tag                                                          = new Tag("var")
  val video: Tag                                                           = new Tag("video")
  val wbr: Tag                                                             = new Tag("wbr")
  def element(tag: String): Tag                                            = new Tag(tag)

  // --- Attribute helpers ---

  val id: PartialAttribute                           = new PartialAttribute("id")
  val `class`: PartialAttribute                      = new PartialAttribute("class")
  val className: PartialAttribute                    = new PartialAttribute("class")
  val styleAttr: PartialAttribute                    = new PartialAttribute("style")
  val titleAttr: PartialAttribute                    = new PartialAttribute("title")
  val href: PartialAttribute                         = new PartialAttribute("href")
  val src: PartialAttribute                          = new PartialAttribute("src")
  val alt: PartialAttribute                          = new PartialAttribute("alt")
  val width: PartialAttribute                        = new PartialAttribute("width")
  val height: PartialAttribute                       = new PartialAttribute("height")
  val action: PartialAttribute                       = new PartialAttribute("action")
  val method: PartialAttribute                       = new PartialAttribute("method")
  val name: PartialAttribute                         = new PartialAttribute("name")
  val value: PartialAttribute                        = new PartialAttribute("value")
  val `type`: PartialAttribute                       = new PartialAttribute("type")
  val typeAttr: PartialAttribute                     = new PartialAttribute("type")
  val placeholder: PartialAttribute                  = new PartialAttribute("placeholder")
  val required: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("required")
  val disabled: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("disabled")
  val readonly: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("readonly")
  val checked: Dom.Attribute.BooleanAttribute        = Dom.boolAttr("checked")
  val selected: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("selected")
  val multiple: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("multiple")
  val min: PartialAttribute                          = new PartialAttribute("min")
  val max: PartialAttribute                          = new PartialAttribute("max")
  val step: PartialAttribute                         = new PartialAttribute("step")
  val pattern: PartialAttribute                      = new PartialAttribute("pattern")
  val autofocus: Dom.Attribute.BooleanAttribute      = Dom.boolAttr("autofocus")
  val autoComplete: PartialAttribute                 = new PartialAttribute("autocomplete")
  val target: PartialAttribute                       = new PartialAttribute("target")
  val rel: PartialAttribute                          = new PartialAttribute("rel")
  val download: PartialAttribute                     = new PartialAttribute("download")
  val role: PartialAttribute                         = new PartialAttribute("role")
  val tabIndex: PartialAttribute                     = new PartialAttribute("tabindex")
  val hidden: Dom.Attribute.BooleanAttribute         = Dom.boolAttr("hidden")
  val draggable: PartialAttribute                    = new PartialAttribute("draggable")
  val contentEditable: PartialAttribute              = new PartialAttribute("contenteditable")
  val lang: PartialAttribute                         = new PartialAttribute("lang")
  val dir: PartialAttribute                          = new PartialAttribute("dir")
  val colspan: PartialAttribute                      = new PartialAttribute("colspan")
  val rowspan: PartialAttribute                      = new PartialAttribute("rowspan")
  val `scope`: PartialAttribute                      = new PartialAttribute("scope")
  val scopeAttr: PartialAttribute                    = new PartialAttribute("scope")
  val headers: PartialAttribute                      = new PartialAttribute("headers")
  val `for`: PartialAttribute                        = new PartialAttribute("for")
  val forAttr: PartialAttribute                      = new PartialAttribute("for")
  val encType: PartialAttribute                      = new PartialAttribute("enctype")
  val formAction: PartialAttribute                   = new PartialAttribute("formaction")
  val formMethod: PartialAttribute                   = new PartialAttribute("formmethod")
  val loading: PartialAttribute                      = new PartialAttribute("loading")
  val srcSet: PartialAttribute                       = new PartialAttribute("srcset")
  val sizes: PartialAttribute                        = new PartialAttribute("sizes")
  val minLength: PartialAttribute                    = new PartialAttribute("minlength")
  val maxLength: PartialAttribute                    = new PartialAttribute("maxlength")
  val size: PartialAttribute                         = new PartialAttribute("size")
  val cols: PartialAttribute                         = new PartialAttribute("cols")
  val rows: PartialAttribute                         = new PartialAttribute("rows")
  val wrap: PartialAttribute                         = new PartialAttribute("wrap")
  val accept: PartialAttribute                       = new PartialAttribute("accept")
  val accesskey: PartialAttribute                    = new PartialAttribute("accesskey")
  val async: Dom.Attribute.BooleanAttribute          = Dom.boolAttr("async")
  val autoplay: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("autoplay")
  val charset: PartialAttribute                      = new PartialAttribute("charset")
  val content: PartialAttribute                      = new PartialAttribute("content")
  val controls: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("controls")
  val crossorigin: PartialAttribute                  = new PartialAttribute("crossorigin")
  val datetime: PartialAttribute                     = new PartialAttribute("datetime")
  val defer: Dom.Attribute.BooleanAttribute          = Dom.boolAttr("defer")
  val formAttr: PartialAttribute                     = new PartialAttribute("form")
  val formNoValidate: Dom.Attribute.BooleanAttribute = Dom.boolAttr("formnovalidate")
  val high: PartialAttribute                         = new PartialAttribute("high")
  val httpEquiv: PartialAttribute                    = new PartialAttribute("http-equiv")
  val integrity: PartialAttribute                    = new PartialAttribute("integrity")
  val labelAttr: PartialAttribute                    = new PartialAttribute("label")
  val list: PartialAttribute                         = new PartialAttribute("list")
  val loop: Dom.Attribute.BooleanAttribute           = Dom.boolAttr("loop")
  val low: PartialAttribute                          = new PartialAttribute("low")
  val media: PartialAttribute                        = new PartialAttribute("media")
  val muted: Dom.Attribute.BooleanAttribute          = Dom.boolAttr("muted")
  val noValidate: Dom.Attribute.BooleanAttribute     = Dom.boolAttr("novalidate")
  val open: Dom.Attribute.BooleanAttribute           = Dom.boolAttr("open")
  val optimum: PartialAttribute                      = new PartialAttribute("optimum")
  val poster: PartialAttribute                       = new PartialAttribute("poster")
  val preload: PartialAttribute                      = new PartialAttribute("preload")
  val referrerpolicy: PartialAttribute               = new PartialAttribute("referrerpolicy")
  val reversed: Dom.Attribute.BooleanAttribute       = Dom.boolAttr("reversed")
  val sandbox: PartialAttribute                      = new PartialAttribute("sandbox")
  val spanAttr: PartialAttribute                     = new PartialAttribute("span")
  val spellcheck: PartialAttribute                   = new PartialAttribute("spellcheck")
  val summaryAttr: PartialAttribute                  = new PartialAttribute("summary")
  val translate: PartialAttribute                    = new PartialAttribute("translate")
  val citeAttr: PartialAttribute                     = new PartialAttribute("cite")
  val slotAttr: PartialAttribute                     = new PartialAttribute("slot")
  val xmlns: PartialAttribute                        = new PartialAttribute("xmlns")

  // --- Multi-value attribute helpers ---

  val ariaDescribedby: PartialMultiAttribute =
    new PartialMultiAttribute("aria-describedby", Dom.AttributeSeparator.Space)
  val ariaLabelledby: PartialMultiAttribute = new PartialMultiAttribute("aria-labelledby", Dom.AttributeSeparator.Space)

  def multiAttr(name: String): PartialMultiAttribute                                             = Dom.multiAttr(name)
  def multiAttr(name: String, separator: Dom.AttributeSeparator): PartialMultiAttribute          = Dom.multiAttr(name, separator)
  def multiAttr(name: String, values: Iterable[String]): Dom.Attribute                           = Dom.multiAttr(name, values)
  def multiAttr(name: String, separator: Dom.AttributeSeparator, values: String*): Dom.Attribute =
    Dom.multiAttr(name, separator, values: _*)

  // --- DOM helper functions ---

  val empty: Dom = Dom.Empty

  def aria(name: String): PartialAttribute     = new PartialAttribute("aria-" + name)
  def dataAttr(name: String): PartialAttribute = new PartialAttribute("data-" + name)
  def attr(name: String): PartialAttribute     = new PartialAttribute(name)
}
