package zio.blocks.template

trait HtmlElements {

  // --- Element constructors ---

  private def el(tag: String, modifiers: Seq[Modifier]): Dom.Element = {
    var elem = Dom.Element(tag, Vector.empty, Vector.empty)
    var i    = 0
    while (i < modifiers.length) {
      elem = modifiers(i).applyTo(elem)
      i += 1
    }
    elem
  }

  def html(modifiers: Modifier*): Dom.Element       = el("html", modifiers)
  def head(modifiers: Modifier*): Dom.Element       = el("head", modifiers)
  def body(modifiers: Modifier*): Dom.Element       = el("body", modifiers)
  def title(modifiers: Modifier*): Dom.Element      = el("title", modifiers)
  def div(modifiers: Modifier*): Dom.Element        = el("div", modifiers)
  def span(modifiers: Modifier*): Dom.Element       = el("span", modifiers)
  def p(modifiers: Modifier*): Dom.Element          = el("p", modifiers)
  def h1(modifiers: Modifier*): Dom.Element         = el("h1", modifiers)
  def h2(modifiers: Modifier*): Dom.Element         = el("h2", modifiers)
  def h3(modifiers: Modifier*): Dom.Element         = el("h3", modifiers)
  def h4(modifiers: Modifier*): Dom.Element         = el("h4", modifiers)
  def h5(modifiers: Modifier*): Dom.Element         = el("h5", modifiers)
  def h6(modifiers: Modifier*): Dom.Element         = el("h6", modifiers)
  def a(modifiers: Modifier*): Dom.Element          = el("a", modifiers)
  def img(modifiers: Modifier*): Dom.Element        = el("img", modifiers)
  def ul(modifiers: Modifier*): Dom.Element         = el("ul", modifiers)
  def ol(modifiers: Modifier*): Dom.Element         = el("ol", modifiers)
  def li(modifiers: Modifier*): Dom.Element         = el("li", modifiers)
  def table(modifiers: Modifier*): Dom.Element      = el("table", modifiers)
  def thead(modifiers: Modifier*): Dom.Element      = el("thead", modifiers)
  def tbody(modifiers: Modifier*): Dom.Element      = el("tbody", modifiers)
  def tfoot(modifiers: Modifier*): Dom.Element      = el("tfoot", modifiers)
  def tr(modifiers: Modifier*): Dom.Element         = el("tr", modifiers)
  def th(modifiers: Modifier*): Dom.Element         = el("th", modifiers)
  def td(modifiers: Modifier*): Dom.Element         = el("td", modifiers)
  def form(modifiers: Modifier*): Dom.Element       = el("form", modifiers)
  def input(modifiers: Modifier*): Dom.Element      = el("input", modifiers)
  def button(modifiers: Modifier*): Dom.Element     = el("button", modifiers)
  def select(modifiers: Modifier*): Dom.Element     = el("select", modifiers)
  def option(modifiers: Modifier*): Dom.Element     = el("option", modifiers)
  def textarea(modifiers: Modifier*): Dom.Element   = el("textarea", modifiers)
  def label(modifiers: Modifier*): Dom.Element      = el("label", modifiers)
  def br(modifiers: Modifier*): Dom.Element         = el("br", modifiers)
  def hr(modifiers: Modifier*): Dom.Element         = el("hr", modifiers)
  def pre(modifiers: Modifier*): Dom.Element        = el("pre", modifiers)
  def code(modifiers: Modifier*): Dom.Element       = el("code", modifiers)
  def strong(modifiers: Modifier*): Dom.Element     = el("strong", modifiers)
  def em(modifiers: Modifier*): Dom.Element         = el("em", modifiers)
  def blockquote(modifiers: Modifier*): Dom.Element = el("blockquote", modifiers)
  def section(modifiers: Modifier*): Dom.Element    = el("section", modifiers)
  def article(modifiers: Modifier*): Dom.Element    = el("article", modifiers)
  def nav(modifiers: Modifier*): Dom.Element        = el("nav", modifiers)
  def header(modifiers: Modifier*): Dom.Element     = el("header", modifiers)
  def footer(modifiers: Modifier*): Dom.Element     = el("footer", modifiers)
  def main(modifiers: Modifier*): Dom.Element       = el("main", modifiers)
  def aside(modifiers: Modifier*): Dom.Element      = el("aside", modifiers)
  def details(modifiers: Modifier*): Dom.Element    = el("details", modifiers)
  def summary(modifiers: Modifier*): Dom.Element    = el("summary", modifiers)
  def dl(modifiers: Modifier*): Dom.Element         = el("dl", modifiers)
  def dt(modifiers: Modifier*): Dom.Element         = el("dt", modifiers)
  def dd(modifiers: Modifier*): Dom.Element         = el("dd", modifiers)
  def figure(modifiers: Modifier*): Dom.Element     = el("figure", modifiers)
  def figcaption(modifiers: Modifier*): Dom.Element = el("figcaption", modifiers)
  def canvas(modifiers: Modifier*): Dom.Element     = el("canvas", modifiers)
  def video(modifiers: Modifier*): Dom.Element      = el("video", modifiers)
  def audio(modifiers: Modifier*): Dom.Element      = el("audio", modifiers)
  def source(modifiers: Modifier*): Dom.Element     = el("source", modifiers)
  def script(modifiers: Modifier*): Dom.Element     = el("script", modifiers)
  def style(modifiers: Modifier*): Dom.Element      = el("style", modifiers)
  def link(modifiers: Modifier*): Dom.Element       = el("link", modifiers)
  def meta(modifiers: Modifier*): Dom.Element       = el("meta", modifiers)
  def small(modifiers: Modifier*): Dom.Element      = el("small", modifiers)
  def sub(modifiers: Modifier*): Dom.Element        = el("sub", modifiers)
  def sup(modifiers: Modifier*): Dom.Element        = el("sup", modifiers)
  def mark(modifiers: Modifier*): Dom.Element       = el("mark", modifiers)
  def del(modifiers: Modifier*): Dom.Element        = el("del", modifiers)
  def ins(modifiers: Modifier*): Dom.Element        = el("ins", modifiers)
  def fieldset(modifiers: Modifier*): Dom.Element   = el("fieldset", modifiers)
  def legend(modifiers: Modifier*): Dom.Element     = el("legend", modifiers)
  def dialog(modifiers: Modifier*): Dom.Element     = el("dialog", modifiers)
  def template_(modifiers: Modifier*): Dom.Element  = el("template", modifiers)
  def slot(modifiers: Modifier*): Dom.Element       = el("slot", modifiers)
  def caption(modifiers: Modifier*): Dom.Element    = el("caption", modifiers)

  // --- Attribute helpers ---

  val id: PartialAttribute              = new PartialAttribute("id")
  val className: PartialAttribute       = new PartialAttribute("class")
  val style: PartialAttribute           = new PartialAttribute("style")
  val title_ : PartialAttribute         = new PartialAttribute("title")
  val href: PartialAttribute            = new PartialAttribute("href")
  val src: PartialAttribute             = new PartialAttribute("src")
  val alt: PartialAttribute             = new PartialAttribute("alt")
  val width: PartialAttribute           = new PartialAttribute("width")
  val height: PartialAttribute          = new PartialAttribute("height")
  val action: PartialAttribute          = new PartialAttribute("action")
  val method: PartialAttribute          = new PartialAttribute("method")
  val name: PartialAttribute            = new PartialAttribute("name")
  val value: PartialAttribute           = new PartialAttribute("value")
  val type_ : PartialAttribute          = new PartialAttribute("type")
  val placeholder: PartialAttribute     = new PartialAttribute("placeholder")
  val required: PartialAttribute        = new PartialAttribute("required")
  val disabled: PartialAttribute        = new PartialAttribute("disabled")
  val readonly: PartialAttribute        = new PartialAttribute("readonly")
  val checked: PartialAttribute         = new PartialAttribute("checked")
  val selected: PartialAttribute        = new PartialAttribute("selected")
  val multiple: PartialAttribute        = new PartialAttribute("multiple")
  val min: PartialAttribute             = new PartialAttribute("min")
  val max: PartialAttribute             = new PartialAttribute("max")
  val step: PartialAttribute            = new PartialAttribute("step")
  val pattern: PartialAttribute         = new PartialAttribute("pattern")
  val autofocus: PartialAttribute       = new PartialAttribute("autofocus")
  val autoComplete: PartialAttribute    = new PartialAttribute("autocomplete")
  val target: PartialAttribute          = new PartialAttribute("target")
  val rel: PartialAttribute             = new PartialAttribute("rel")
  val download: PartialAttribute        = new PartialAttribute("download")
  val role: PartialAttribute            = new PartialAttribute("role")
  val tabIndex: PartialAttribute        = new PartialAttribute("tabindex")
  val hidden: PartialAttribute          = new PartialAttribute("hidden")
  val draggable: PartialAttribute       = new PartialAttribute("draggable")
  val contentEditable: PartialAttribute = new PartialAttribute("contenteditable")
  val lang: PartialAttribute            = new PartialAttribute("lang")
  val dir: PartialAttribute             = new PartialAttribute("dir")
  val colspan: PartialAttribute         = new PartialAttribute("colspan")
  val rowspan: PartialAttribute         = new PartialAttribute("rowspan")
  val scope_ : PartialAttribute         = new PartialAttribute("scope")
  val headers: PartialAttribute         = new PartialAttribute("headers")
  val for_ : PartialAttribute           = new PartialAttribute("for")
  val encType: PartialAttribute         = new PartialAttribute("enctype")
  val formAction: PartialAttribute      = new PartialAttribute("formaction")
  val formMethod: PartialAttribute      = new PartialAttribute("formmethod")
  val loading: PartialAttribute         = new PartialAttribute("loading")
  val srcSet: PartialAttribute          = new PartialAttribute("srcset")
  val sizes: PartialAttribute           = new PartialAttribute("sizes")
  val minLength: PartialAttribute       = new PartialAttribute("minlength")
  val maxLength: PartialAttribute       = new PartialAttribute("maxlength")
  val size: PartialAttribute            = new PartialAttribute("size")
  val cols: PartialAttribute            = new PartialAttribute("cols")
  val rows: PartialAttribute            = new PartialAttribute("rows")
  val wrap: PartialAttribute            = new PartialAttribute("wrap")
}
