package zio.blocks.template

trait HtmlElements {

  // --- Element constructors ---

  private def el(tag: String, modifiers: Seq[Modifier]): Dom.Element = {
    var elem: Dom.Element = Dom.Element.Generic(tag, Vector.empty, Vector.empty)
    var i                 = 0
    while (i < modifiers.length) {
      elem = modifiers(i).applyTo(elem)
      i += 1
    }
    elem
  }

  private def elScript(modifiers: Seq[Modifier]): Dom.Element.Script = {
    var elem: Dom.Element = Dom.Element.Script(Vector.empty, Vector.empty)
    var i                 = 0
    while (i < modifiers.length) {
      elem = modifiers(i).applyTo(elem)
      i += 1
    }
    elem.asInstanceOf[Dom.Element.Script]
  }

  private def elStyle(modifiers: Seq[Modifier]): Dom.Element.Style = {
    var elem: Dom.Element = Dom.Element.Style(Vector.empty, Vector.empty)
    var i                 = 0
    while (i < modifiers.length) {
      elem = modifiers(i).applyTo(elem)
      i += 1
    }
    elem.asInstanceOf[Dom.Element.Style]
  }

  def html(modifiers: Modifier*): Dom.Element                 = el("html", modifiers)
  def head(modifiers: Modifier*): Dom.Element                 = el("head", modifiers)
  def body(modifiers: Modifier*): Dom.Element                 = el("body", modifiers)
  def title(modifiers: Modifier*): Dom.Element                = el("title", modifiers)
  def div(modifiers: Modifier*): Dom.Element                  = el("div", modifiers)
  def span(modifiers: Modifier*): Dom.Element                 = el("span", modifiers)
  def p(modifiers: Modifier*): Dom.Element                    = el("p", modifiers)
  def h1(modifiers: Modifier*): Dom.Element                   = el("h1", modifiers)
  def h2(modifiers: Modifier*): Dom.Element                   = el("h2", modifiers)
  def h3(modifiers: Modifier*): Dom.Element                   = el("h3", modifiers)
  def h4(modifiers: Modifier*): Dom.Element                   = el("h4", modifiers)
  def h5(modifiers: Modifier*): Dom.Element                   = el("h5", modifiers)
  def h6(modifiers: Modifier*): Dom.Element                   = el("h6", modifiers)
  def a(modifiers: Modifier*): Dom.Element                    = el("a", modifiers)
  def abbr(modifiers: Modifier*): Dom.Element                 = el("abbr", modifiers)
  def address(modifiers: Modifier*): Dom.Element              = el("address", modifiers)
  def area(modifiers: Modifier*): Dom.Element                 = el("area", modifiers)
  def article(modifiers: Modifier*): Dom.Element              = el("article", modifiers)
  def aside(modifiers: Modifier*): Dom.Element                = el("aside", modifiers)
  def audio(modifiers: Modifier*): Dom.Element                = el("audio", modifiers)
  def b(modifiers: Modifier*): Dom.Element                    = el("b", modifiers)
  def base(modifiers: Modifier*): Dom.Element                 = el("base", modifiers)
  def bdi(modifiers: Modifier*): Dom.Element                  = el("bdi", modifiers)
  def bdo(modifiers: Modifier*): Dom.Element                  = el("bdo", modifiers)
  def blockquote(modifiers: Modifier*): Dom.Element           = el("blockquote", modifiers)
  def br(modifiers: Modifier*): Dom.Element                   = el("br", modifiers)
  def button(modifiers: Modifier*): Dom.Element               = el("button", modifiers)
  def canvas(modifiers: Modifier*): Dom.Element               = el("canvas", modifiers)
  def caption(modifiers: Modifier*): Dom.Element              = el("caption", modifiers)
  def cite(modifiers: Modifier*): Dom.Element                 = el("cite", modifiers)
  def code(modifiers: Modifier*): Dom.Element                 = el("code", modifiers)
  def col(modifiers: Modifier*): Dom.Element                  = el("col", modifiers)
  def colgroup(modifiers: Modifier*): Dom.Element             = el("colgroup", modifiers)
  def data(modifiers: Modifier*): Dom.Element                 = el("data", modifiers)
  def datalist(modifiers: Modifier*): Dom.Element             = el("datalist", modifiers)
  def dd(modifiers: Modifier*): Dom.Element                   = el("dd", modifiers)
  def del(modifiers: Modifier*): Dom.Element                  = el("del", modifiers)
  def details(modifiers: Modifier*): Dom.Element              = el("details", modifiers)
  def dfn(modifiers: Modifier*): Dom.Element                  = el("dfn", modifiers)
  def dialog(modifiers: Modifier*): Dom.Element               = el("dialog", modifiers)
  def dl(modifiers: Modifier*): Dom.Element                   = el("dl", modifiers)
  def dt(modifiers: Modifier*): Dom.Element                   = el("dt", modifiers)
  def em(modifiers: Modifier*): Dom.Element                   = el("em", modifiers)
  def embed(modifiers: Modifier*): Dom.Element                = el("embed", modifiers)
  def fieldset(modifiers: Modifier*): Dom.Element             = el("fieldset", modifiers)
  def figure(modifiers: Modifier*): Dom.Element               = el("figure", modifiers)
  def figcaption(modifiers: Modifier*): Dom.Element           = el("figcaption", modifiers)
  def footer(modifiers: Modifier*): Dom.Element               = el("footer", modifiers)
  def form(modifiers: Modifier*): Dom.Element                 = el("form", modifiers)
  def header(modifiers: Modifier*): Dom.Element               = el("header", modifiers)
  def hr(modifiers: Modifier*): Dom.Element                   = el("hr", modifiers)
  def i(modifiers: Modifier*): Dom.Element                    = el("i", modifiers)
  def iframe(modifiers: Modifier*): Dom.Element               = el("iframe", modifiers)
  def img(modifiers: Modifier*): Dom.Element                  = el("img", modifiers)
  def input(modifiers: Modifier*): Dom.Element                = el("input", modifiers)
  def ins(modifiers: Modifier*): Dom.Element                  = el("ins", modifiers)
  def kbd(modifiers: Modifier*): Dom.Element                  = el("kbd", modifiers)
  def label(modifiers: Modifier*): Dom.Element                = el("label", modifiers)
  def legend(modifiers: Modifier*): Dom.Element               = el("legend", modifiers)
  def li(modifiers: Modifier*): Dom.Element                   = el("li", modifiers)
  def link(modifiers: Modifier*): Dom.Element                 = el("link", modifiers)
  def main(modifiers: Modifier*): Dom.Element                 = el("main", modifiers)
  def map(modifiers: Modifier*): Dom.Element                  = el("map", modifiers)
  def mark(modifiers: Modifier*): Dom.Element                 = el("mark", modifiers)
  def math(modifiers: Modifier*): Dom.Element                 = el("math", modifiers)
  def meta(modifiers: Modifier*): Dom.Element                 = el("meta", modifiers)
  def meter(modifiers: Modifier*): Dom.Element                = el("meter", modifiers)
  def nav(modifiers: Modifier*): Dom.Element                  = el("nav", modifiers)
  def noscript(modifiers: Modifier*): Dom.Element             = el("noscript", modifiers)
  def `object`(modifiers: Modifier*): Dom.Element             = el("object", modifiers)
  def objectTag(modifiers: Modifier*): Dom.Element            = el("object", modifiers)
  def ol(modifiers: Modifier*): Dom.Element                   = el("ol", modifiers)
  def optgroup(modifiers: Modifier*): Dom.Element             = el("optgroup", modifiers)
  def option(modifiers: Modifier*): Dom.Element               = el("option", modifiers)
  def output(modifiers: Modifier*): Dom.Element               = el("output", modifiers)
  def param(modifiers: Modifier*): Dom.Element                = el("param", modifiers)
  def picture(modifiers: Modifier*): Dom.Element              = el("picture", modifiers)
  def pre(modifiers: Modifier*): Dom.Element                  = el("pre", modifiers)
  def progress(modifiers: Modifier*): Dom.Element             = el("progress", modifiers)
  def q(modifiers: Modifier*): Dom.Element                    = el("q", modifiers)
  def rp(modifiers: Modifier*): Dom.Element                   = el("rp", modifiers)
  def rt(modifiers: Modifier*): Dom.Element                   = el("rt", modifiers)
  def ruby(modifiers: Modifier*): Dom.Element                 = el("ruby", modifiers)
  def s(modifiers: Modifier*): Dom.Element                    = el("s", modifiers)
  def samp(modifiers: Modifier*): Dom.Element                 = el("samp", modifiers)
  def script(modifiers: Modifier*): Dom.Element.Script        = elScript(modifiers)
  def search(modifiers: Modifier*): Dom.Element               = el("search", modifiers)
  def section(modifiers: Modifier*): Dom.Element              = el("section", modifiers)
  def select(modifiers: Modifier*): Dom.Element               = el("select", modifiers)
  def slot(modifiers: Modifier*): Dom.Element                 = el("slot", modifiers)
  def small(modifiers: Modifier*): Dom.Element                = el("small", modifiers)
  def source(modifiers: Modifier*): Dom.Element               = el("source", modifiers)
  def strong(modifiers: Modifier*): Dom.Element               = el("strong", modifiers)
  def style(modifiers: Modifier*): Dom.Element.Style          = elStyle(modifiers)
  def sub(modifiers: Modifier*): Dom.Element                  = el("sub", modifiers)
  def summary(modifiers: Modifier*): Dom.Element              = el("summary", modifiers)
  def sup(modifiers: Modifier*): Dom.Element                  = el("sup", modifiers)
  def svg(modifiers: Modifier*): Dom.Element                  = el("svg", modifiers)
  def table(modifiers: Modifier*): Dom.Element                = el("table", modifiers)
  def tbody(modifiers: Modifier*): Dom.Element                = el("tbody", modifiers)
  def td(modifiers: Modifier*): Dom.Element                   = el("td", modifiers)
  def `template`(modifiers: Modifier*): Dom.Element           = el("template", modifiers)
  def templateTag(modifiers: Modifier*): Dom.Element          = el("template", modifiers)
  def textarea(modifiers: Modifier*): Dom.Element             = el("textarea", modifiers)
  def tfoot(modifiers: Modifier*): Dom.Element                = el("tfoot", modifiers)
  def th(modifiers: Modifier*): Dom.Element                   = el("th", modifiers)
  def thead(modifiers: Modifier*): Dom.Element                = el("thead", modifiers)
  def time(modifiers: Modifier*): Dom.Element                 = el("time", modifiers)
  def tr(modifiers: Modifier*): Dom.Element                   = el("tr", modifiers)
  def track(modifiers: Modifier*): Dom.Element                = el("track", modifiers)
  def u(modifiers: Modifier*): Dom.Element                    = el("u", modifiers)
  def ul(modifiers: Modifier*): Dom.Element                   = el("ul", modifiers)
  def `var`(modifiers: Modifier*): Dom.Element                = el("var", modifiers)
  def varTag(modifiers: Modifier*): Dom.Element               = el("var", modifiers)
  def video(modifiers: Modifier*): Dom.Element                = el("video", modifiers)
  def wbr(modifiers: Modifier*): Dom.Element                  = el("wbr", modifiers)
  def element(tag: String, modifiers: Modifier*): Dom.Element = el(tag, modifiers)

  // --- Attribute helpers ---

  val id: PartialAttribute              = new PartialAttribute("id")
  val `class`: PartialAttribute         = new PartialAttribute("class")
  val className: PartialAttribute       = new PartialAttribute("class")
  val styleAttr: PartialAttribute       = new PartialAttribute("style")
  val titleAttr: PartialAttribute       = new PartialAttribute("title")
  val href: PartialAttribute            = new PartialAttribute("href")
  val src: PartialAttribute             = new PartialAttribute("src")
  val alt: PartialAttribute             = new PartialAttribute("alt")
  val width: PartialAttribute           = new PartialAttribute("width")
  val height: PartialAttribute          = new PartialAttribute("height")
  val action: PartialAttribute          = new PartialAttribute("action")
  val method: PartialAttribute          = new PartialAttribute("method")
  val name: PartialAttribute            = new PartialAttribute("name")
  val value: PartialAttribute           = new PartialAttribute("value")
  val `type`: PartialAttribute          = new PartialAttribute("type")
  val typeAttr: PartialAttribute        = new PartialAttribute("type")
  val placeholder: PartialAttribute     = new PartialAttribute("placeholder")
  val required: PartialAttribute        = new PartialAttribute("required")
  val disabled: PartialAttribute        = new PartialAttribute("disabled")
  val readonly: PartialAttribute        = new PartialAttribute("readonly")
  val checked: PartialAttribute         = new PartialAttribute("checked")
  val selected: PartialAttribute        = new PartialAttribute("selected")
  val multiple: PartialAttribute        = new PartialAttribute("multiple")
  val min: PartialAttribute             = new PartialAttribute("min")
  val max: PartialAttribute             = new PartialAttribute("max")
  val step: PartialAttribute            = new PartialAttribute("step")
  val pattern: PartialAttribute         = new PartialAttribute("pattern")
  val autofocus: PartialAttribute       = new PartialAttribute("autofocus")
  val autoComplete: PartialAttribute    = new PartialAttribute("autocomplete")
  val target: PartialAttribute          = new PartialAttribute("target")
  val rel: PartialAttribute             = new PartialAttribute("rel")
  val download: PartialAttribute        = new PartialAttribute("download")
  val role: PartialAttribute            = new PartialAttribute("role")
  val tabIndex: PartialAttribute        = new PartialAttribute("tabindex")
  val hidden: PartialAttribute          = new PartialAttribute("hidden")
  val draggable: PartialAttribute       = new PartialAttribute("draggable")
  val contentEditable: PartialAttribute = new PartialAttribute("contenteditable")
  val lang: PartialAttribute            = new PartialAttribute("lang")
  val dir: PartialAttribute             = new PartialAttribute("dir")
  val colspan: PartialAttribute         = new PartialAttribute("colspan")
  val rowspan: PartialAttribute         = new PartialAttribute("rowspan")
  val `scope`: PartialAttribute         = new PartialAttribute("scope")
  val scopeAttr: PartialAttribute       = new PartialAttribute("scope")
  val headers: PartialAttribute         = new PartialAttribute("headers")
  val `for`: PartialAttribute           = new PartialAttribute("for")
  val forAttr: PartialAttribute         = new PartialAttribute("for")
  val encType: PartialAttribute         = new PartialAttribute("enctype")
  val formAction: PartialAttribute      = new PartialAttribute("formaction")
  val formMethod: PartialAttribute      = new PartialAttribute("formmethod")
  val loading: PartialAttribute         = new PartialAttribute("loading")
  val srcSet: PartialAttribute          = new PartialAttribute("srcset")
  val sizes: PartialAttribute           = new PartialAttribute("sizes")
  val minLength: PartialAttribute       = new PartialAttribute("minlength")
  val maxLength: PartialAttribute       = new PartialAttribute("maxlength")
  val size: PartialAttribute            = new PartialAttribute("size")
  val cols: PartialAttribute            = new PartialAttribute("cols")
  val rows: PartialAttribute            = new PartialAttribute("rows")
  val wrap: PartialAttribute            = new PartialAttribute("wrap")
  val accept: PartialAttribute          = new PartialAttribute("accept")
  val accesskey: PartialAttribute       = new PartialAttribute("accesskey")
  val async: PartialAttribute           = new PartialAttribute("async")
  val autoplay: PartialAttribute        = new PartialAttribute("autoplay")
  val charset: PartialAttribute         = new PartialAttribute("charset")
  val content: PartialAttribute         = new PartialAttribute("content")
  val controls: PartialAttribute        = new PartialAttribute("controls")
  val crossorigin: PartialAttribute     = new PartialAttribute("crossorigin")
  val datetime: PartialAttribute        = new PartialAttribute("datetime")
  val defer: PartialAttribute           = new PartialAttribute("defer")
  val formAttr: PartialAttribute        = new PartialAttribute("form")
  val formNoValidate: PartialAttribute  = new PartialAttribute("formnovalidate")
  val high: PartialAttribute            = new PartialAttribute("high")
  val httpEquiv: PartialAttribute       = new PartialAttribute("http-equiv")
  val integrity: PartialAttribute       = new PartialAttribute("integrity")
  val labelAttr: PartialAttribute       = new PartialAttribute("label")
  val list: PartialAttribute            = new PartialAttribute("list")
  val loop: PartialAttribute            = new PartialAttribute("loop")
  val low: PartialAttribute             = new PartialAttribute("low")
  val media: PartialAttribute           = new PartialAttribute("media")
  val muted: PartialAttribute           = new PartialAttribute("muted")
  val noValidate: PartialAttribute      = new PartialAttribute("novalidate")
  val open: PartialAttribute            = new PartialAttribute("open")
  val optimum: PartialAttribute         = new PartialAttribute("optimum")
  val poster: PartialAttribute          = new PartialAttribute("poster")
  val preload: PartialAttribute         = new PartialAttribute("preload")
  val referrerpolicy: PartialAttribute  = new PartialAttribute("referrerpolicy")
  val reversed: PartialAttribute        = new PartialAttribute("reversed")
  val sandbox: PartialAttribute         = new PartialAttribute("sandbox")
  val spanAttr: PartialAttribute        = new PartialAttribute("span")
  val spellcheck: PartialAttribute      = new PartialAttribute("spellcheck")
  val summaryAttr: PartialAttribute     = new PartialAttribute("summary")
  val translate: PartialAttribute       = new PartialAttribute("translate")
  val citeAttr: PartialAttribute        = new PartialAttribute("cite")
  val slotAttr: PartialAttribute        = new PartialAttribute("slot")
  val xmlns: PartialAttribute           = new PartialAttribute("xmlns")

  // --- Multi-value attribute helpers ---

  val ariaDescribedby: PartialMultiAttribute =
    new PartialMultiAttribute("aria-describedby", Dom.AttributeSeparator.Space)
  val ariaLabelledby: PartialMultiAttribute = new PartialMultiAttribute("aria-labelledby", Dom.AttributeSeparator.Space)

  def multiAttr(name: String): PartialMultiAttribute                                             = Dom.multiAttr(name)
  def multiAttr(name: String, separator: Dom.AttributeSeparator): PartialMultiAttribute          = Dom.multiAttr(name, separator)
  def multiAttr(name: String, values: Iterable[String]): Dom.Attribute                           = Dom.multiAttr(name, values)
  def multiAttr(name: String, separator: Dom.AttributeSeparator, values: String*): Dom.Attribute =
    Dom.multiAttr(name, separator, values: _*)

  // --- DOM helper functions ---

  def raw(content: String): Dom.RawHtml = Dom.RawHtml(content)
  def fragment(children: Dom*): Dom     = Dom.fragment(children.toVector)
  val empty: Dom                        = Dom.Empty

  def aria(name: String): PartialAttribute     = new PartialAttribute("aria-" + name)
  def dataAttr(name: String): PartialAttribute = new PartialAttribute("data-" + name)
  def attr(name: String): PartialAttribute     = new PartialAttribute(name)
}
