package golem:agent;

interface common {
  use golem:rpc/types@0.2.2.{value-and-type, wit-type, wit-value};

  type url = string;

  enum agent-mode {
    durable,
    ephemeral
  }

  record agent-type {
    type-name:    string,
    description:  string,
    %constructor: agent-constructor,
    methods:      list<agent-method>,
    dependencies: list<agent-dependency>,
    mode:         agent-mode,
  }

  record agent-dependency {
    type-name:    string,
    description:  option<string>,
    %constructor: agent-constructor,
    methods:      list<agent-method>,
  }

  record agent-method {
    name:          string,
    description:   string,
    prompt-hint:   option<string>,
    input-schema:  data-schema,
    output-schema: data-schema,
  }

  record agent-constructor {
    name:          option<string>,
    description:   string,
    prompt-hint:   option<string>,
    input-schema:  data-schema,
  }

  variant data-schema {
    /// List of named elements
    %tuple(list<tuple<string, element-schema>>),
    /// List of named variants that can be used 0 or more times in a multimodal `data-value`
    multimodal(list<tuple<string, element-schema>>),
  }

  variant data-value {
    /// List of element values, each corresponding to an element of the tuple `data-schema`
    %tuple(list<element-value>),
    /// List of element values and their schema names; each name points to one named element of the corresponding
    /// multimodal `data-schema`.
    multimodal(list<tuple<string, element-value>>),
  }

  variant element-schema {
    component-model(wit-type),
    unstructured-text(text-descriptor),
    unstructured-binary(binary-descriptor),
  }

  variant element-value {
    component-model(wit-value),
    unstructured-text(text-reference),
    unstructured-binary(binary-reference),
  }

  record text-type {
    language-code: string,
  }

  variant text-reference {
    url(string),
    inline(text-source),
  }

  record text-source {
    data:      string,
    text-type: option<text-type>,
  }

  record text-descriptor {
    restrictions: option<list<text-type>>,
  }

  record binary-descriptor {
    restrictions: option<list<binary-type>>,
  }

  record binary-type {
    mime-type: string,
  }

  variant binary-reference {
    url(url),
    inline(binary-source),
  }

  record binary-source {
    data:        list<u8>,
    binary-type: binary-type,
  }

  variant agent-error {
    invalid-input(string),
    invalid-method(string),
    invalid-type(string),
    invalid-agent-id(string),
    custom-error(value-and-type),
  }
}

interface host {
  use golem:rpc/types@0.2.2.{component-id, uuid};
  use common.{agent-error, agent-type, data-value};

  /// Associates an agent type with a component that implements it
  record registered-agent-type {
    agent-type: agent-type,
    implemented-by: component-id
  }

  /// Gets all the registered agent types
  get-all-agent-types: func() -> list<registered-agent-type>;

  /// Get a specific registered agent type by name
  get-agent-type: func(agent-type-name: string) -> option<registered-agent-type>;

  /// Constructs a string agent-id from the agent type and its constructor parameters
  /// and an optional phantom ID
  make-agent-id: func(agent-type-name: string, input: data-value, phantom-id: option<uuid>) -> result<string, agent-error>;

  /// Parses an agent-id (created by `make-agent-id`) into an agent type name and its constructor parameters
  /// and an optional phantom ID
  parse-agent-id: func(agent-id: string) -> result<tuple<string, data-value, option<uuid>>, agent-error>;
}

interface guest {
  use common.{agent-error, agent-type, data-value};

  /// Initializes the agent of a given type with the given constructor parameters.
  /// If called a second time, it fails.
  initialize: func(agent-type: string, input: data-value) -> result<_, agent-error>;

  /// Invokes an agent. If create was not called before, it fails
  invoke: func(method-name: string, input: data-value) -> result<data-value, agent-error>;

  /// Gets the agent type. If create was not called before, it fails
  get-definition: func() -> agent-type;

  /// Gets the agent types defined by this component
  discover-agent-types: func() -> result<list<agent-type>, agent-error>;
}

world agent-guest {
  import golem:api/host@1.3.0;
  import golem:rpc/types@0.2.2;
  import host;

  import golem:rdbms/postgres@0.0.1;
  import golem:rdbms/mysql@0.0.1;
  import golem:rdbms/types@0.0.1;

  import golem:api/context@1.3.0;
  import golem:api/oplog@1.3.0;
  import golem:durability/durability@1.3.0;

  import wasi:cli/environment@0.2.3;

  import wasi:blobstore/blobstore;
  import wasi:blobstore/container;
  import wasi:blobstore/types;

  import wasi:keyvalue/eventual@0.1.0;
  import wasi:keyvalue/eventual-batch@0.1.0;
  import wasi:keyvalue/types@0.1.0;
  import wasi:keyvalue/wasi-keyvalue-error@0.1.0;

  import wasi:config/store@0.2.0-draft;

  import golem:llm/llm@1.0.0;
  import golem:web-search/web-search@1.0.0;
  import golem:web-search/types@1.0.0;
  import golem:embed/embed@1.0.0;
  import golem:graph/connection@1.0.0;
  import golem:graph/schema@1.0.0;
  import golem:video-generation/video-generation@1.0.0;
  import golem:video-generation/lip-sync@1.0.0;
  import golem:video-generation/advanced@1.0.0;

  export guest;
  export golem:api/save-snapshot@1.3.0;
  export golem:api/load-snapshot@1.3.0;
}

